#!/usr/bin/env bash
#Install nginx and configure its reponse header

apt-get -y update
apt-get -y install nginx
sed -i '/#/d' /etc/nginx/sites-available/default
sed -i "s/listen 80 default_server;/&\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-available/default
service nginx restart
