#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get update
apt-get install haproxy=2.0.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 88570-web-01 18.235.234.1:80 check
        server 88570-web-02 54.144.148.192:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
